/*
Notion API

Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BlockGetDetailsResponseHeading2RichTextInnerAnnotations } from './block-get-details-response-heading2-rich-text-inner-annotations';
import { BlockGetDetailsResponseHeading2RichTextInnerText } from './block-get-details-response-heading2-rich-text-inner-text';

/**
 * 
 * @export
 * @interface BlockGetDetailsResponseHeading2RichTextInner
 */
export interface BlockGetDetailsResponseHeading2RichTextInner {
    /**
     * 
     * @type {string}
     * @memberof BlockGetDetailsResponseHeading2RichTextInner
     */
    'type'?: string;
    /**
     * 
     * @type {BlockGetDetailsResponseHeading2RichTextInnerText}
     * @memberof BlockGetDetailsResponseHeading2RichTextInner
     */
    'text'?: BlockGetDetailsResponseHeading2RichTextInnerText;
    /**
     * 
     * @type {BlockGetDetailsResponseHeading2RichTextInnerAnnotations}
     * @memberof BlockGetDetailsResponseHeading2RichTextInner
     */
    'annotations'?: BlockGetDetailsResponseHeading2RichTextInnerAnnotations;
    /**
     * 
     * @type {string}
     * @memberof BlockGetDetailsResponseHeading2RichTextInner
     */
    'plain_text'?: string;
    /**
     * 
     * @type {any}
     * @memberof BlockGetDetailsResponseHeading2RichTextInner
     */
    'href'?: any;
}

