/*
Notion API

Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BlockUpdateBlockByIdResponseHeading2RichTextInner } from './block-update-block-by-id-response-heading2-rich-text-inner';

/**
 * 
 * @export
 * @interface BlockUpdateBlockByIdResponseHeading2
 */
export interface BlockUpdateBlockByIdResponseHeading2 {
    /**
     * 
     * @type {Array<BlockUpdateBlockByIdResponseHeading2RichTextInner>}
     * @memberof BlockUpdateBlockByIdResponseHeading2
     */
    'rich_text'?: Array<BlockUpdateBlockByIdResponseHeading2RichTextInner>;
    /**
     * 
     * @type {string}
     * @memberof BlockUpdateBlockByIdResponseHeading2
     */
    'color'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof BlockUpdateBlockByIdResponseHeading2
     */
    'is_toggleable'?: boolean;
}

