/*
Notion API

Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BlockRemoveBlockByIdResponseParagraph
 */
export interface BlockRemoveBlockByIdResponseParagraph {
    /**
     * 
     * @type {Array<any>}
     * @memberof BlockRemoveBlockByIdResponseParagraph
     */
    'rich_text'?: Array<any>;
    /**
     * 
     * @type {string}
     * @memberof BlockRemoveBlockByIdResponseParagraph
     */
    'color'?: string;
}

