/*
Notion API

Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BlockGetDetailsResponseCreatedBy } from './block-get-details-response-created-by';
import { BlockGetDetailsResponseHeading2 } from './block-get-details-response-heading2';
import { BlockGetDetailsResponseLastEditedBy } from './block-get-details-response-last-edited-by';
import { BlockGetDetailsResponseParent } from './block-get-details-response-parent';

/**
 * 
 * @export
 * @interface BlockGetDetailsResponse
 */
export interface BlockGetDetailsResponse {
    /**
     * 
     * @type {string}
     * @memberof BlockGetDetailsResponse
     */
    'object'?: string;
    /**
     * 
     * @type {string}
     * @memberof BlockGetDetailsResponse
     */
    'id'?: string;
    /**
     * 
     * @type {BlockGetDetailsResponseParent}
     * @memberof BlockGetDetailsResponse
     */
    'parent'?: BlockGetDetailsResponseParent;
    /**
     * 
     * @type {string}
     * @memberof BlockGetDetailsResponse
     */
    'created_time'?: string;
    /**
     * 
     * @type {string}
     * @memberof BlockGetDetailsResponse
     */
    'last_edited_time'?: string;
    /**
     * 
     * @type {BlockGetDetailsResponseCreatedBy}
     * @memberof BlockGetDetailsResponse
     */
    'created_by'?: BlockGetDetailsResponseCreatedBy;
    /**
     * 
     * @type {BlockGetDetailsResponseLastEditedBy}
     * @memberof BlockGetDetailsResponse
     */
    'last_edited_by'?: BlockGetDetailsResponseLastEditedBy;
    /**
     * 
     * @type {boolean}
     * @memberof BlockGetDetailsResponse
     */
    'has_children'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BlockGetDetailsResponse
     */
    'archived'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof BlockGetDetailsResponse
     */
    'type'?: string;
    /**
     * 
     * @type {BlockGetDetailsResponseHeading2}
     * @memberof BlockGetDetailsResponse
     */
    'heading_2'?: BlockGetDetailsResponseHeading2;
}

