/*
Notion API

Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BlockGetDetailsResponseHeading2RichTextInner } from './block-get-details-response-heading2-rich-text-inner';

/**
 * 
 * @export
 * @interface BlockGetDetailsResponseHeading2
 */
export interface BlockGetDetailsResponseHeading2 {
    /**
     * 
     * @type {Array<BlockGetDetailsResponseHeading2RichTextInner>}
     * @memberof BlockGetDetailsResponseHeading2
     */
    'rich_text'?: Array<BlockGetDetailsResponseHeading2RichTextInner>;
    /**
     * 
     * @type {string}
     * @memberof BlockGetDetailsResponseHeading2
     */
    'color'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof BlockGetDetailsResponseHeading2
     */
    'is_toggleable'?: boolean;
}

