/*
Notion API

Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BlockGetDetailsResponseHeading2RichTextInnerAnnotations
 */
export interface BlockGetDetailsResponseHeading2RichTextInnerAnnotations {
    /**
     * 
     * @type {boolean}
     * @memberof BlockGetDetailsResponseHeading2RichTextInnerAnnotations
     */
    'bold'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BlockGetDetailsResponseHeading2RichTextInnerAnnotations
     */
    'italic'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BlockGetDetailsResponseHeading2RichTextInnerAnnotations
     */
    'strikethrough'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BlockGetDetailsResponseHeading2RichTextInnerAnnotations
     */
    'underline'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BlockGetDetailsResponseHeading2RichTextInnerAnnotations
     */
    'code'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof BlockGetDetailsResponseHeading2RichTextInnerAnnotations
     */
    'color'?: string;
}

