/*
Notion API

Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CommentGetListResponseResultsInner } from './comment-get-list-response-results-inner';

/**
 * 
 * @export
 * @interface CommentGetListResponse
 */
export interface CommentGetListResponse {
    /**
     * 
     * @type {string}
     * @memberof CommentGetListResponse
     */
    'object'?: string;
    /**
     * 
     * @type {Array<CommentGetListResponseResultsInner>}
     * @memberof CommentGetListResponse
     */
    'results'?: Array<CommentGetListResponseResultsInner>;
    /**
     * 
     * @type {any}
     * @memberof CommentGetListResponse
     */
    'next_cursor'?: any;
    /**
     * 
     * @type {boolean}
     * @memberof CommentGetListResponse
     */
    'has_more'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CommentGetListResponse
     */
    'type'?: string;
    /**
     * 
     * @type {object}
     * @memberof CommentGetListResponse
     */
    'comment'?: object;
}

