/*
Notion API

Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CommentCreateNewResponseRichTextInnerAnnotations } from './comment-create-new-response-rich-text-inner-annotations';
import { CommentCreateNewResponseRichTextInnerText } from './comment-create-new-response-rich-text-inner-text';

/**
 * 
 * @export
 * @interface CommentCreateNewResponseRichTextInner
 */
export interface CommentCreateNewResponseRichTextInner {
    /**
     * 
     * @type {string}
     * @memberof CommentCreateNewResponseRichTextInner
     */
    'type'?: string;
    /**
     * 
     * @type {CommentCreateNewResponseRichTextInnerText}
     * @memberof CommentCreateNewResponseRichTextInner
     */
    'text'?: CommentCreateNewResponseRichTextInnerText;
    /**
     * 
     * @type {CommentCreateNewResponseRichTextInnerAnnotations}
     * @memberof CommentCreateNewResponseRichTextInner
     */
    'annotations'?: CommentCreateNewResponseRichTextInnerAnnotations;
    /**
     * 
     * @type {string}
     * @memberof CommentCreateNewResponseRichTextInner
     */
    'plain_text'?: string;
    /**
     * 
     * @type {any}
     * @memberof CommentCreateNewResponseRichTextInner
     */
    'href'?: any;
}

