/*
Notion API

Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CommentCreateNewResponseCreatedBy } from './comment-create-new-response-created-by';
import { CommentCreateNewResponseParent } from './comment-create-new-response-parent';
import { CommentCreateNewResponseRichTextInner } from './comment-create-new-response-rich-text-inner';

/**
 * 
 * @export
 * @interface CommentCreateNewResponse
 */
export interface CommentCreateNewResponse {
    /**
     * 
     * @type {string}
     * @memberof CommentCreateNewResponse
     */
    'object'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommentCreateNewResponse
     */
    'id'?: string;
    /**
     * 
     * @type {CommentCreateNewResponseParent}
     * @memberof CommentCreateNewResponse
     */
    'parent'?: CommentCreateNewResponseParent;
    /**
     * 
     * @type {string}
     * @memberof CommentCreateNewResponse
     */
    'discussion_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommentCreateNewResponse
     */
    'created_time'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommentCreateNewResponse
     */
    'last_edited_time'?: string;
    /**
     * 
     * @type {CommentCreateNewResponseCreatedBy}
     * @memberof CommentCreateNewResponse
     */
    'created_by'?: CommentCreateNewResponseCreatedBy;
    /**
     * 
     * @type {Array<CommentCreateNewResponseRichTextInner>}
     * @memberof CommentCreateNewResponse
     */
    'rich_text'?: Array<CommentCreateNewResponseRichTextInner>;
}

