/*
Notion API

Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DatabaseGetDatabaseResponsePropertiesNumberOfMealsRollup } from './database-get-database-response-properties-number-of-meals-rollup';

/**
 * 
 * @export
 * @interface DatabaseGetDatabaseResponsePropertiesNumberOfMeals
 */
export interface DatabaseGetDatabaseResponsePropertiesNumberOfMeals {
    /**
     * 
     * @type {string}
     * @memberof DatabaseGetDatabaseResponsePropertiesNumberOfMeals
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof DatabaseGetDatabaseResponsePropertiesNumberOfMeals
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof DatabaseGetDatabaseResponsePropertiesNumberOfMeals
     */
    'type'?: string;
    /**
     * 
     * @type {DatabaseGetDatabaseResponsePropertiesNumberOfMealsRollup}
     * @memberof DatabaseGetDatabaseResponsePropertiesNumberOfMeals
     */
    'rollup'?: DatabaseGetDatabaseResponsePropertiesNumberOfMealsRollup;
}

