/*
Notion API

Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DatabaseGetDatabaseResponsePropertiesInStock
 */
export interface DatabaseGetDatabaseResponsePropertiesInStock {
    /**
     * 
     * @type {string}
     * @memberof DatabaseGetDatabaseResponsePropertiesInStock
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof DatabaseGetDatabaseResponsePropertiesInStock
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof DatabaseGetDatabaseResponsePropertiesInStock
     */
    'type'?: string;
    /**
     * 
     * @type {object}
     * @memberof DatabaseGetDatabaseResponsePropertiesInStock
     */
    'checkbox'?: object;
}

