/*
Notion API

Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DatabaseExecuteQueryRequest
 */
export interface DatabaseExecuteQueryRequest {
    /**
     * When supplied, limits which pages are returned based on the [filter conditions](ref:post-database-query-filter).
     * @type {string}
     * @memberof DatabaseExecuteQueryRequest
     */
    'filter'?: string;
    /**
     * When supplied, orders the results based on the provided [sort criteria](ref:post-database-query-sort).
     * @type {Array<any>}
     * @memberof DatabaseExecuteQueryRequest
     */
    'sorts'?: Array<any>;
    /**
     * When supplied, returns a page of results starting after the cursor provided. If not supplied, this endpoint will return the first page of results.
     * @type {string}
     * @memberof DatabaseExecuteQueryRequest
     */
    'start_cursor'?: string;
    /**
     * The number of items from the full list desired in the response. Maximum: 100
     * @type {number}
     * @memberof DatabaseExecuteQueryRequest
     */
    'page_size'?: number;
}

