/*
Notion API

Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DatabaseGetDatabaseResponseDescriptionInnerAnnotations } from './database-get-database-response-description-inner-annotations';
import { DatabaseGetDatabaseResponseDescriptionInnerText } from './database-get-database-response-description-inner-text';

/**
 * 
 * @export
 * @interface DatabaseGetDatabaseResponseDescriptionInner
 */
export interface DatabaseGetDatabaseResponseDescriptionInner {
    /**
     * 
     * @type {string}
     * @memberof DatabaseGetDatabaseResponseDescriptionInner
     */
    'type'?: string;
    /**
     * 
     * @type {DatabaseGetDatabaseResponseDescriptionInnerText}
     * @memberof DatabaseGetDatabaseResponseDescriptionInner
     */
    'text'?: DatabaseGetDatabaseResponseDescriptionInnerText;
    /**
     * 
     * @type {DatabaseGetDatabaseResponseDescriptionInnerAnnotations}
     * @memberof DatabaseGetDatabaseResponseDescriptionInner
     */
    'annotations'?: DatabaseGetDatabaseResponseDescriptionInnerAnnotations;
    /**
     * 
     * @type {string}
     * @memberof DatabaseGetDatabaseResponseDescriptionInner
     */
    'plain_text'?: string;
    /**
     * 
     * @type {any}
     * @memberof DatabaseGetDatabaseResponseDescriptionInner
     */
    'href'?: any;
}

