/*
Notion API

Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DatabaseUpdateDatabase400ResponseOneOf1
 */
export interface DatabaseUpdateDatabase400ResponseOneOf1 {
    /**
     * 
     * @type {string}
     * @memberof DatabaseUpdateDatabase400ResponseOneOf1
     */
    'object'?: string;
    /**
     * 
     * @type {number}
     * @memberof DatabaseUpdateDatabase400ResponseOneOf1
     */
    'status'?: number;
    /**
     * 
     * @type {string}
     * @memberof DatabaseUpdateDatabase400ResponseOneOf1
     */
    'code'?: string;
    /**
     * 
     * @type {string}
     * @memberof DatabaseUpdateDatabase400ResponseOneOf1
     */
    'message'?: string;
}

