/*
Notion API

Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DatabaseGetDatabaseResponsePropertiesFoodGroupSelectOptionsInner } from './database-get-database-response-properties-food-group-select-options-inner';

/**
 * 
 * @export
 * @interface DatabaseGetDatabaseResponsePropertiesFoodGroupSelect
 */
export interface DatabaseGetDatabaseResponsePropertiesFoodGroupSelect {
    /**
     * 
     * @type {Array<DatabaseGetDatabaseResponsePropertiesFoodGroupSelectOptionsInner>}
     * @memberof DatabaseGetDatabaseResponsePropertiesFoodGroupSelect
     */
    'options'?: Array<DatabaseGetDatabaseResponsePropertiesFoodGroupSelectOptionsInner>;
}

