/*
Notion API

Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DatabaseGetDatabaseResponsePropertiesFoodGroupSelect } from './database-get-database-response-properties-food-group-select';

/**
 * 
 * @export
 * @interface DatabaseGetDatabaseResponsePropertiesFoodGroup
 */
export interface DatabaseGetDatabaseResponsePropertiesFoodGroup {
    /**
     * 
     * @type {string}
     * @memberof DatabaseGetDatabaseResponsePropertiesFoodGroup
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof DatabaseGetDatabaseResponsePropertiesFoodGroup
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof DatabaseGetDatabaseResponsePropertiesFoodGroup
     */
    'type'?: string;
    /**
     * 
     * @type {DatabaseGetDatabaseResponsePropertiesFoodGroupSelect}
     * @memberof DatabaseGetDatabaseResponsePropertiesFoodGroup
     */
    'select'?: DatabaseGetDatabaseResponsePropertiesFoodGroupSelect;
}

