/*
Notion API

Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DatabaseGetDatabaseResponseIcon
 */
export interface DatabaseGetDatabaseResponseIcon {
    /**
     * 
     * @type {string}
     * @memberof DatabaseGetDatabaseResponseIcon
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof DatabaseGetDatabaseResponseIcon
     */
    'emoji'?: string;
}

