/*
Notion API

Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DatabaseGetDatabaseResponseProperties1 } from './database-get-database-response-properties1';
import { DatabaseGetDatabaseResponsePropertiesDescription } from './database-get-database-response-properties-description';
import { DatabaseGetDatabaseResponsePropertiesFoodGroup } from './database-get-database-response-properties-food-group';
import { DatabaseGetDatabaseResponsePropertiesInStock } from './database-get-database-response-properties-in-stock';
import { DatabaseGetDatabaseResponsePropertiesLastOrdered } from './database-get-database-response-properties-last-ordered';
import { DatabaseGetDatabaseResponsePropertiesMeals } from './database-get-database-response-properties-meals';
import { DatabaseGetDatabaseResponsePropertiesName } from './database-get-database-response-properties-name';
import { DatabaseGetDatabaseResponsePropertiesNumberOfMeals } from './database-get-database-response-properties-number-of-meals';
import { DatabaseGetDatabaseResponsePropertiesPhoto } from './database-get-database-response-properties-photo';
import { DatabaseGetDatabaseResponsePropertiesPrice } from './database-get-database-response-properties-price';
import { DatabaseGetDatabaseResponsePropertiesStoreAvailability } from './database-get-database-response-properties-store-availability';

/**
 * 
 * @export
 * @interface DatabaseGetDatabaseResponseProperties
 */
export interface DatabaseGetDatabaseResponseProperties {
    /**
     * 
     * @type {DatabaseGetDatabaseResponseProperties1}
     * @memberof DatabaseGetDatabaseResponseProperties
     */
    '+1'?: DatabaseGetDatabaseResponseProperties1;
    /**
     * 
     * @type {DatabaseGetDatabaseResponsePropertiesInStock}
     * @memberof DatabaseGetDatabaseResponseProperties
     */
    'In stock'?: DatabaseGetDatabaseResponsePropertiesInStock;
    /**
     * 
     * @type {DatabaseGetDatabaseResponsePropertiesPrice}
     * @memberof DatabaseGetDatabaseResponseProperties
     */
    'Price'?: DatabaseGetDatabaseResponsePropertiesPrice;
    /**
     * 
     * @type {DatabaseGetDatabaseResponsePropertiesDescription}
     * @memberof DatabaseGetDatabaseResponseProperties
     */
    'Description'?: DatabaseGetDatabaseResponsePropertiesDescription;
    /**
     * 
     * @type {DatabaseGetDatabaseResponsePropertiesLastOrdered}
     * @memberof DatabaseGetDatabaseResponseProperties
     */
    'Last ordered'?: DatabaseGetDatabaseResponsePropertiesLastOrdered;
    /**
     * 
     * @type {DatabaseGetDatabaseResponsePropertiesMeals}
     * @memberof DatabaseGetDatabaseResponseProperties
     */
    'Meals'?: DatabaseGetDatabaseResponsePropertiesMeals;
    /**
     * 
     * @type {DatabaseGetDatabaseResponsePropertiesNumberOfMeals}
     * @memberof DatabaseGetDatabaseResponseProperties
     */
    'Number of meals'?: DatabaseGetDatabaseResponsePropertiesNumberOfMeals;
    /**
     * 
     * @type {DatabaseGetDatabaseResponsePropertiesStoreAvailability}
     * @memberof DatabaseGetDatabaseResponseProperties
     */
    'Store availability'?: DatabaseGetDatabaseResponsePropertiesStoreAvailability;
    /**
     * 
     * @type {DatabaseGetDatabaseResponsePropertiesPhoto}
     * @memberof DatabaseGetDatabaseResponseProperties
     */
    'Photo'?: DatabaseGetDatabaseResponsePropertiesPhoto;
    /**
     * 
     * @type {DatabaseGetDatabaseResponsePropertiesFoodGroup}
     * @memberof DatabaseGetDatabaseResponseProperties
     */
    'Food group'?: DatabaseGetDatabaseResponsePropertiesFoodGroup;
    /**
     * 
     * @type {DatabaseGetDatabaseResponsePropertiesName}
     * @memberof DatabaseGetDatabaseResponseProperties
     */
    'Name'?: DatabaseGetDatabaseResponsePropertiesName;
}

