/*
Notion API

Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DatabaseGetDatabaseResponseTitleInnerAnnotations } from './database-get-database-response-title-inner-annotations';
import { DatabaseGetDatabaseResponseTitleInnerText } from './database-get-database-response-title-inner-text';

/**
 * 
 * @export
 * @interface DatabaseGetDatabaseResponseTitleInner
 */
export interface DatabaseGetDatabaseResponseTitleInner {
    /**
     * 
     * @type {string}
     * @memberof DatabaseGetDatabaseResponseTitleInner
     */
    'type'?: string;
    /**
     * 
     * @type {DatabaseGetDatabaseResponseTitleInnerText}
     * @memberof DatabaseGetDatabaseResponseTitleInner
     */
    'text'?: DatabaseGetDatabaseResponseTitleInnerText;
    /**
     * 
     * @type {DatabaseGetDatabaseResponseTitleInnerAnnotations}
     * @memberof DatabaseGetDatabaseResponseTitleInner
     */
    'annotations'?: DatabaseGetDatabaseResponseTitleInnerAnnotations;
    /**
     * 
     * @type {string}
     * @memberof DatabaseGetDatabaseResponseTitleInner
     */
    'plain_text'?: string;
    /**
     * 
     * @type {any}
     * @memberof DatabaseGetDatabaseResponseTitleInner
     */
    'href'?: any;
}

