/*
Notion API

Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DatabaseUpdateDatabase400ResponseOneOf } from './database-update-database400-response-one-of';
import { DatabaseUpdateDatabase400ResponseOneOf1 } from './database-update-database400-response-one-of1';

/**
 * @type DatabaseUpdateDatabase400Response
 * @export
 */
export type DatabaseUpdateDatabase400Response = DatabaseUpdateDatabase400ResponseOneOf | DatabaseUpdateDatabase400ResponseOneOf1;


