/*
Notion API

Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DatabaseGetDatabaseResponsePropertiesPriceNumber } from './database-get-database-response-properties-price-number';

/**
 * 
 * @export
 * @interface DatabaseGetDatabaseResponsePropertiesPrice
 */
export interface DatabaseGetDatabaseResponsePropertiesPrice {
    /**
     * 
     * @type {string}
     * @memberof DatabaseGetDatabaseResponsePropertiesPrice
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof DatabaseGetDatabaseResponsePropertiesPrice
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof DatabaseGetDatabaseResponsePropertiesPrice
     */
    'type'?: string;
    /**
     * 
     * @type {DatabaseGetDatabaseResponsePropertiesPriceNumber}
     * @memberof DatabaseGetDatabaseResponsePropertiesPrice
     */
    'number'?: DatabaseGetDatabaseResponsePropertiesPriceNumber;
}

