/*
Notion API

Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DatabaseCreateNewDatabaseRequest
 */
export interface DatabaseCreateNewDatabaseRequest {
    /**
     * Title of database as it appears in Notion. An array of [rich text objects](ref:rich-text).
     * @type {Array<any>}
     * @memberof DatabaseCreateNewDatabaseRequest
     */
    'title'?: Array<any>;
    /**
     * A [page parent](/reference/database#page-parent)
     * @type {string}
     * @memberof DatabaseCreateNewDatabaseRequest
     */
    'parent': string;
    /**
     * Property schema of database. The keys are the names of properties as they appear in Notion and the values are [property schema objects](https://developers.notion.com/reference/property-schema-object).
     * @type {string}
     * @memberof DatabaseCreateNewDatabaseRequest
     */
    'properties': string;
}

