/*
Notion API

Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DatabaseGetDatabaseResponsePropertiesStoreAvailabilityMultiSelect } from './database-get-database-response-properties-store-availability-multi-select';

/**
 * 
 * @export
 * @interface DatabaseGetDatabaseResponsePropertiesStoreAvailability
 */
export interface DatabaseGetDatabaseResponsePropertiesStoreAvailability {
    /**
     * 
     * @type {string}
     * @memberof DatabaseGetDatabaseResponsePropertiesStoreAvailability
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof DatabaseGetDatabaseResponsePropertiesStoreAvailability
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof DatabaseGetDatabaseResponsePropertiesStoreAvailability
     */
    'type'?: string;
    /**
     * 
     * @type {DatabaseGetDatabaseResponsePropertiesStoreAvailabilityMultiSelect}
     * @memberof DatabaseGetDatabaseResponsePropertiesStoreAvailability
     */
    'multi_select'?: DatabaseGetDatabaseResponsePropertiesStoreAvailabilityMultiSelect;
}

