/*
Notion API

Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DatabaseGetDatabaseResponseCoverExternal } from './database-get-database-response-cover-external';

/**
 * 
 * @export
 * @interface DatabaseGetDatabaseResponseCover
 */
export interface DatabaseGetDatabaseResponseCover {
    /**
     * 
     * @type {string}
     * @memberof DatabaseGetDatabaseResponseCover
     */
    'type'?: string;
    /**
     * 
     * @type {DatabaseGetDatabaseResponseCoverExternal}
     * @memberof DatabaseGetDatabaseResponseCover
     */
    'external'?: DatabaseGetDatabaseResponseCoverExternal;
}

