/*
Notion API

Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DatabaseGetDatabaseResponsePropertiesPhoto
 */
export interface DatabaseGetDatabaseResponsePropertiesPhoto {
    /**
     * 
     * @type {string}
     * @memberof DatabaseGetDatabaseResponsePropertiesPhoto
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof DatabaseGetDatabaseResponsePropertiesPhoto
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof DatabaseGetDatabaseResponsePropertiesPhoto
     */
    'type'?: string;
    /**
     * 
     * @type {object}
     * @memberof DatabaseGetDatabaseResponsePropertiesPhoto
     */
    'files'?: object;
}

