/*
Notion API

Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DatabaseGetDatabaseResponsePropertiesMealsRelation } from './database-get-database-response-properties-meals-relation';

/**
 * 
 * @export
 * @interface DatabaseGetDatabaseResponsePropertiesMeals
 */
export interface DatabaseGetDatabaseResponsePropertiesMeals {
    /**
     * 
     * @type {string}
     * @memberof DatabaseGetDatabaseResponsePropertiesMeals
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof DatabaseGetDatabaseResponsePropertiesMeals
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof DatabaseGetDatabaseResponsePropertiesMeals
     */
    'type'?: string;
    /**
     * 
     * @type {DatabaseGetDatabaseResponsePropertiesMealsRelation}
     * @memberof DatabaseGetDatabaseResponsePropertiesMeals
     */
    'relation'?: DatabaseGetDatabaseResponsePropertiesMealsRelation;
}

