/*
Notion API

Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PageGetPageResponsePropertiesDescriptionRichTextInnerAnnotations } from './page-get-page-response-properties-description-rich-text-inner-annotations';
import { PageGetPageResponsePropertiesDescriptionRichTextInnerText } from './page-get-page-response-properties-description-rich-text-inner-text';

/**
 * 
 * @export
 * @interface PageGetPageResponsePropertiesDescriptionRichTextInner
 */
export interface PageGetPageResponsePropertiesDescriptionRichTextInner {
    /**
     * 
     * @type {string}
     * @memberof PageGetPageResponsePropertiesDescriptionRichTextInner
     */
    'type'?: string;
    /**
     * 
     * @type {PageGetPageResponsePropertiesDescriptionRichTextInnerText}
     * @memberof PageGetPageResponsePropertiesDescriptionRichTextInner
     */
    'text'?: PageGetPageResponsePropertiesDescriptionRichTextInnerText;
    /**
     * 
     * @type {PageGetPageResponsePropertiesDescriptionRichTextInnerAnnotations}
     * @memberof PageGetPageResponsePropertiesDescriptionRichTextInner
     */
    'annotations'?: PageGetPageResponsePropertiesDescriptionRichTextInnerAnnotations;
    /**
     * 
     * @type {string}
     * @memberof PageGetPageResponsePropertiesDescriptionRichTextInner
     */
    'plain_text'?: string;
    /**
     * 
     * @type {any}
     * @memberof PageGetPageResponsePropertiesDescriptionRichTextInner
     */
    'href'?: any;
}

