/*
Notion API

Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PageUpdatePropertiesRequest
 */
export interface PageUpdatePropertiesRequest {
    /**
     * The property values to update for the page. The keys are the names or IDs of the property and the values are property values. If a page property ID is not included, then it is not changed.
     * @type {string}
     * @memberof PageUpdatePropertiesRequest
     */
    'properties'?: string;
    /**
     * Whether the page is archived (deleted). Set to true to archive a page. Set to false to un-archive (restore) a page.
     * @type {boolean}
     * @memberof PageUpdatePropertiesRequest
     */
    'archived'?: boolean;
    /**
     * A page icon for the page. Supported types are [external file object](https://developers.notion.com/reference/file-object) or [emoji object](https://developers.notion.com/reference/emoji-object).
     * @type {string}
     * @memberof PageUpdatePropertiesRequest
     */
    'icon'?: string;
    /**
     * A cover image for the page. Only [external file objects](https://developers.notion.com/reference/file-object) are supported.
     * @type {string}
     * @memberof PageUpdatePropertiesRequest
     */
    'cover'?: string;
}

