/*
Notion API

Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PageUpdatePropertiesResponsePropertiesCostOfNextTrip } from './page-update-properties-response-properties-cost-of-next-trip';
import { PageUpdatePropertiesResponsePropertiesDescription } from './page-update-properties-response-properties-description';
import { PageUpdatePropertiesResponsePropertiesFoodGroup } from './page-update-properties-response-properties-food-group';
import { PageUpdatePropertiesResponsePropertiesInStock } from './page-update-properties-response-properties-in-stock';
import { PageUpdatePropertiesResponsePropertiesLastOrdered } from './page-update-properties-response-properties-last-ordered';
import { PageUpdatePropertiesResponsePropertiesName } from './page-update-properties-response-properties-name';
import { PageUpdatePropertiesResponsePropertiesNumberOfMeals } from './page-update-properties-response-properties-number-of-meals';
import { PageUpdatePropertiesResponsePropertiesPhoto } from './page-update-properties-response-properties-photo';
import { PageUpdatePropertiesResponsePropertiesPrice } from './page-update-properties-response-properties-price';
import { PageUpdatePropertiesResponsePropertiesRecipes } from './page-update-properties-response-properties-recipes';
import { PageUpdatePropertiesResponsePropertiesResponsiblePerson } from './page-update-properties-response-properties-responsible-person';
import { PageUpdatePropertiesResponsePropertiesStoreAvailability } from './page-update-properties-response-properties-store-availability';

/**
 * 
 * @export
 * @interface PageUpdatePropertiesResponseProperties
 */
export interface PageUpdatePropertiesResponseProperties {
    /**
     * 
     * @type {PageUpdatePropertiesResponsePropertiesStoreAvailability}
     * @memberof PageUpdatePropertiesResponseProperties
     */
    'Store availability'?: PageUpdatePropertiesResponsePropertiesStoreAvailability;
    /**
     * 
     * @type {PageUpdatePropertiesResponsePropertiesFoodGroup}
     * @memberof PageUpdatePropertiesResponseProperties
     */
    'Food group'?: PageUpdatePropertiesResponsePropertiesFoodGroup;
    /**
     * 
     * @type {PageUpdatePropertiesResponsePropertiesPrice}
     * @memberof PageUpdatePropertiesResponseProperties
     */
    'Price'?: PageUpdatePropertiesResponsePropertiesPrice;
    /**
     * 
     * @type {PageUpdatePropertiesResponsePropertiesResponsiblePerson}
     * @memberof PageUpdatePropertiesResponseProperties
     */
    'Responsible Person'?: PageUpdatePropertiesResponsePropertiesResponsiblePerson;
    /**
     * 
     * @type {PageUpdatePropertiesResponsePropertiesLastOrdered}
     * @memberof PageUpdatePropertiesResponseProperties
     */
    'Last ordered'?: PageUpdatePropertiesResponsePropertiesLastOrdered;
    /**
     * 
     * @type {PageUpdatePropertiesResponsePropertiesCostOfNextTrip}
     * @memberof PageUpdatePropertiesResponseProperties
     */
    'Cost of next trip'?: PageUpdatePropertiesResponsePropertiesCostOfNextTrip;
    /**
     * 
     * @type {PageUpdatePropertiesResponsePropertiesRecipes}
     * @memberof PageUpdatePropertiesResponseProperties
     */
    'Recipes'?: PageUpdatePropertiesResponsePropertiesRecipes;
    /**
     * 
     * @type {PageUpdatePropertiesResponsePropertiesDescription}
     * @memberof PageUpdatePropertiesResponseProperties
     */
    'Description'?: PageUpdatePropertiesResponsePropertiesDescription;
    /**
     * 
     * @type {PageUpdatePropertiesResponsePropertiesInStock}
     * @memberof PageUpdatePropertiesResponseProperties
     */
    'In stock'?: PageUpdatePropertiesResponsePropertiesInStock;
    /**
     * 
     * @type {PageUpdatePropertiesResponsePropertiesNumberOfMeals}
     * @memberof PageUpdatePropertiesResponseProperties
     */
    'Number of meals'?: PageUpdatePropertiesResponsePropertiesNumberOfMeals;
    /**
     * 
     * @type {PageUpdatePropertiesResponsePropertiesPhoto}
     * @memberof PageUpdatePropertiesResponseProperties
     */
    'Photo'?: PageUpdatePropertiesResponsePropertiesPhoto;
    /**
     * 
     * @type {PageUpdatePropertiesResponsePropertiesName}
     * @memberof PageUpdatePropertiesResponseProperties
     */
    'Name'?: PageUpdatePropertiesResponsePropertiesName;
}

