/*
Notion API

Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PageGetPageResponsePropertiesLastOrderedDate } from './page-get-page-response-properties-last-ordered-date';

/**
 * 
 * @export
 * @interface PageGetPageResponsePropertiesLastOrdered
 */
export interface PageGetPageResponsePropertiesLastOrdered {
    /**
     * 
     * @type {string}
     * @memberof PageGetPageResponsePropertiesLastOrdered
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof PageGetPageResponsePropertiesLastOrdered
     */
    'type'?: string;
    /**
     * 
     * @type {PageGetPageResponsePropertiesLastOrderedDate}
     * @memberof PageGetPageResponsePropertiesLastOrdered
     */
    'date'?: PageGetPageResponsePropertiesLastOrderedDate;
}

