/*
Notion API

Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PageGetPageResponsePropertiesNumberOfMealsRollup } from './page-get-page-response-properties-number-of-meals-rollup';

/**
 * 
 * @export
 * @interface PageGetPageResponsePropertiesNumberOfMeals
 */
export interface PageGetPageResponsePropertiesNumberOfMeals {
    /**
     * 
     * @type {string}
     * @memberof PageGetPageResponsePropertiesNumberOfMeals
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof PageGetPageResponsePropertiesNumberOfMeals
     */
    'type'?: string;
    /**
     * 
     * @type {PageGetPageResponsePropertiesNumberOfMealsRollup}
     * @memberof PageGetPageResponsePropertiesNumberOfMeals
     */
    'rollup'?: PageGetPageResponsePropertiesNumberOfMealsRollup;
}

