/*
Notion API

Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PageGetPageResponsePropertiesResponsiblePersonPeopleInner } from './page-get-page-response-properties-responsible-person-people-inner';

/**
 * 
 * @export
 * @interface PageGetPageResponsePropertiesResponsiblePerson
 */
export interface PageGetPageResponsePropertiesResponsiblePerson {
    /**
     * 
     * @type {string}
     * @memberof PageGetPageResponsePropertiesResponsiblePerson
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof PageGetPageResponsePropertiesResponsiblePerson
     */
    'type'?: string;
    /**
     * 
     * @type {Array<PageGetPageResponsePropertiesResponsiblePersonPeopleInner>}
     * @memberof PageGetPageResponsePropertiesResponsiblePerson
     */
    'people'?: Array<PageGetPageResponsePropertiesResponsiblePersonPeopleInner>;
}

