/*
Notion API

Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PageGetPageResponsePropertiesCostOfNextTrip } from './page-get-page-response-properties-cost-of-next-trip';
import { PageGetPageResponsePropertiesDescription } from './page-get-page-response-properties-description';
import { PageGetPageResponsePropertiesFoodGroup } from './page-get-page-response-properties-food-group';
import { PageGetPageResponsePropertiesInStock } from './page-get-page-response-properties-in-stock';
import { PageGetPageResponsePropertiesLastOrdered } from './page-get-page-response-properties-last-ordered';
import { PageGetPageResponsePropertiesName } from './page-get-page-response-properties-name';
import { PageGetPageResponsePropertiesNumberOfMeals } from './page-get-page-response-properties-number-of-meals';
import { PageGetPageResponsePropertiesPhoto } from './page-get-page-response-properties-photo';
import { PageGetPageResponsePropertiesPrice } from './page-get-page-response-properties-price';
import { PageGetPageResponsePropertiesRecipes } from './page-get-page-response-properties-recipes';
import { PageGetPageResponsePropertiesResponsiblePerson } from './page-get-page-response-properties-responsible-person';
import { PageGetPageResponsePropertiesStoreAvailability } from './page-get-page-response-properties-store-availability';

/**
 * 
 * @export
 * @interface PageGetPageResponseProperties
 */
export interface PageGetPageResponseProperties {
    /**
     * 
     * @type {PageGetPageResponsePropertiesStoreAvailability}
     * @memberof PageGetPageResponseProperties
     */
    'Store availability'?: PageGetPageResponsePropertiesStoreAvailability;
    /**
     * 
     * @type {PageGetPageResponsePropertiesFoodGroup}
     * @memberof PageGetPageResponseProperties
     */
    'Food group'?: PageGetPageResponsePropertiesFoodGroup;
    /**
     * 
     * @type {PageGetPageResponsePropertiesPrice}
     * @memberof PageGetPageResponseProperties
     */
    'Price'?: PageGetPageResponsePropertiesPrice;
    /**
     * 
     * @type {PageGetPageResponsePropertiesResponsiblePerson}
     * @memberof PageGetPageResponseProperties
     */
    'Responsible Person'?: PageGetPageResponsePropertiesResponsiblePerson;
    /**
     * 
     * @type {PageGetPageResponsePropertiesLastOrdered}
     * @memberof PageGetPageResponseProperties
     */
    'Last ordered'?: PageGetPageResponsePropertiesLastOrdered;
    /**
     * 
     * @type {PageGetPageResponsePropertiesCostOfNextTrip}
     * @memberof PageGetPageResponseProperties
     */
    'Cost of next trip'?: PageGetPageResponsePropertiesCostOfNextTrip;
    /**
     * 
     * @type {PageGetPageResponsePropertiesRecipes}
     * @memberof PageGetPageResponseProperties
     */
    'Recipes'?: PageGetPageResponsePropertiesRecipes;
    /**
     * 
     * @type {PageGetPageResponsePropertiesDescription}
     * @memberof PageGetPageResponseProperties
     */
    'Description'?: PageGetPageResponsePropertiesDescription;
    /**
     * 
     * @type {PageGetPageResponsePropertiesInStock}
     * @memberof PageGetPageResponseProperties
     */
    'In stock'?: PageGetPageResponsePropertiesInStock;
    /**
     * 
     * @type {PageGetPageResponsePropertiesNumberOfMeals}
     * @memberof PageGetPageResponseProperties
     */
    'Number of meals'?: PageGetPageResponsePropertiesNumberOfMeals;
    /**
     * 
     * @type {PageGetPageResponsePropertiesPhoto}
     * @memberof PageGetPageResponseProperties
     */
    'Photo'?: PageGetPageResponsePropertiesPhoto;
    /**
     * 
     * @type {PageGetPageResponsePropertiesName}
     * @memberof PageGetPageResponseProperties
     */
    'Name'?: PageGetPageResponsePropertiesName;
}

