/*
Notion API

Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PageGetPageResponsePropertiesNameTitleInner } from './page-get-page-response-properties-name-title-inner';

/**
 * 
 * @export
 * @interface PageGetPageResponsePropertiesName
 */
export interface PageGetPageResponsePropertiesName {
    /**
     * 
     * @type {Array<PageGetPageResponsePropertiesNameTitleInner>}
     * @memberof PageGetPageResponsePropertiesName
     */
    'title'?: Array<PageGetPageResponsePropertiesNameTitleInner>;
    /**
     * 
     * @type {string}
     * @memberof PageGetPageResponsePropertiesName
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof PageGetPageResponsePropertiesName
     */
    'type'?: string;
}

