/*
Notion API

Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PageCreateNewPageResponsePropertiesCostOfNextTrip } from './page-create-new-page-response-properties-cost-of-next-trip';
import { PageCreateNewPageResponsePropertiesDescription } from './page-create-new-page-response-properties-description';
import { PageCreateNewPageResponsePropertiesFoodGroup } from './page-create-new-page-response-properties-food-group';
import { PageCreateNewPageResponsePropertiesInStock } from './page-create-new-page-response-properties-in-stock';
import { PageCreateNewPageResponsePropertiesLastOrdered } from './page-create-new-page-response-properties-last-ordered';
import { PageCreateNewPageResponsePropertiesName } from './page-create-new-page-response-properties-name';
import { PageCreateNewPageResponsePropertiesNumberOfMeals } from './page-create-new-page-response-properties-number-of-meals';
import { PageCreateNewPageResponsePropertiesPhoto } from './page-create-new-page-response-properties-photo';
import { PageCreateNewPageResponsePropertiesPrice } from './page-create-new-page-response-properties-price';
import { PageCreateNewPageResponsePropertiesRecipes } from './page-create-new-page-response-properties-recipes';
import { PageCreateNewPageResponsePropertiesResponsiblePerson } from './page-create-new-page-response-properties-responsible-person';
import { PageCreateNewPageResponsePropertiesStoreAvailability } from './page-create-new-page-response-properties-store-availability';

/**
 * 
 * @export
 * @interface PageCreateNewPageResponseProperties
 */
export interface PageCreateNewPageResponseProperties {
    /**
     * 
     * @type {PageCreateNewPageResponsePropertiesStoreAvailability}
     * @memberof PageCreateNewPageResponseProperties
     */
    'Store availability'?: PageCreateNewPageResponsePropertiesStoreAvailability;
    /**
     * 
     * @type {PageCreateNewPageResponsePropertiesFoodGroup}
     * @memberof PageCreateNewPageResponseProperties
     */
    'Food group'?: PageCreateNewPageResponsePropertiesFoodGroup;
    /**
     * 
     * @type {PageCreateNewPageResponsePropertiesPrice}
     * @memberof PageCreateNewPageResponseProperties
     */
    'Price'?: PageCreateNewPageResponsePropertiesPrice;
    /**
     * 
     * @type {PageCreateNewPageResponsePropertiesResponsiblePerson}
     * @memberof PageCreateNewPageResponseProperties
     */
    'Responsible Person'?: PageCreateNewPageResponsePropertiesResponsiblePerson;
    /**
     * 
     * @type {PageCreateNewPageResponsePropertiesLastOrdered}
     * @memberof PageCreateNewPageResponseProperties
     */
    'Last ordered'?: PageCreateNewPageResponsePropertiesLastOrdered;
    /**
     * 
     * @type {PageCreateNewPageResponsePropertiesCostOfNextTrip}
     * @memberof PageCreateNewPageResponseProperties
     */
    'Cost of next trip'?: PageCreateNewPageResponsePropertiesCostOfNextTrip;
    /**
     * 
     * @type {PageCreateNewPageResponsePropertiesRecipes}
     * @memberof PageCreateNewPageResponseProperties
     */
    'Recipes'?: PageCreateNewPageResponsePropertiesRecipes;
    /**
     * 
     * @type {PageCreateNewPageResponsePropertiesDescription}
     * @memberof PageCreateNewPageResponseProperties
     */
    'Description'?: PageCreateNewPageResponsePropertiesDescription;
    /**
     * 
     * @type {PageCreateNewPageResponsePropertiesInStock}
     * @memberof PageCreateNewPageResponseProperties
     */
    'In stock'?: PageCreateNewPageResponsePropertiesInStock;
    /**
     * 
     * @type {PageCreateNewPageResponsePropertiesNumberOfMeals}
     * @memberof PageCreateNewPageResponseProperties
     */
    'Number of meals'?: PageCreateNewPageResponsePropertiesNumberOfMeals;
    /**
     * 
     * @type {PageCreateNewPageResponsePropertiesPhoto}
     * @memberof PageCreateNewPageResponseProperties
     */
    'Photo'?: PageCreateNewPageResponsePropertiesPhoto;
    /**
     * 
     * @type {PageCreateNewPageResponsePropertiesName}
     * @memberof PageCreateNewPageResponseProperties
     */
    'Name'?: PageCreateNewPageResponsePropertiesName;
}

