/*
Notion API

Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PageGetPageResponsePropertiesRecipesRelationInner } from './page-get-page-response-properties-recipes-relation-inner';

/**
 * 
 * @export
 * @interface PageGetPageResponsePropertiesRecipes
 */
export interface PageGetPageResponsePropertiesRecipes {
    /**
     * 
     * @type {string}
     * @memberof PageGetPageResponsePropertiesRecipes
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof PageGetPageResponsePropertiesRecipes
     */
    'type'?: string;
    /**
     * 
     * @type {Array<PageGetPageResponsePropertiesRecipesRelationInner>}
     * @memberof PageGetPageResponsePropertiesRecipes
     */
    'relation'?: Array<PageGetPageResponsePropertiesRecipesRelationInner>;
    /**
     * 
     * @type {boolean}
     * @memberof PageGetPageResponsePropertiesRecipes
     */
    'has_more'?: boolean;
}

