/*
Notion API

Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PageGetPageResponsePropertiesNameTitleInnerAnnotations } from './page-get-page-response-properties-name-title-inner-annotations';
import { PageGetPageResponsePropertiesNameTitleInnerText } from './page-get-page-response-properties-name-title-inner-text';

/**
 * 
 * @export
 * @interface PageGetPageResponsePropertiesNameTitleInner
 */
export interface PageGetPageResponsePropertiesNameTitleInner {
    /**
     * 
     * @type {string}
     * @memberof PageGetPageResponsePropertiesNameTitleInner
     */
    'type'?: string;
    /**
     * 
     * @type {PageGetPageResponsePropertiesNameTitleInnerText}
     * @memberof PageGetPageResponsePropertiesNameTitleInner
     */
    'text'?: PageGetPageResponsePropertiesNameTitleInnerText;
    /**
     * 
     * @type {PageGetPageResponsePropertiesNameTitleInnerAnnotations}
     * @memberof PageGetPageResponsePropertiesNameTitleInner
     */
    'annotations'?: PageGetPageResponsePropertiesNameTitleInnerAnnotations;
    /**
     * 
     * @type {string}
     * @memberof PageGetPageResponsePropertiesNameTitleInner
     */
    'plain_text'?: string;
    /**
     * 
     * @type {any}
     * @memberof PageGetPageResponsePropertiesNameTitleInner
     */
    'href'?: any;
}

