/*
Notion API

Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PageGetPageResponseCover } from './page-get-page-response-cover';
import { PageGetPageResponseCreatedBy } from './page-get-page-response-created-by';
import { PageGetPageResponseIcon } from './page-get-page-response-icon';
import { PageGetPageResponseLastEditedBy } from './page-get-page-response-last-edited-by';
import { PageGetPageResponseParent } from './page-get-page-response-parent';
import { PageGetPageResponseProperties } from './page-get-page-response-properties';

/**
 * 
 * @export
 * @interface PageGetPageResponse
 */
export interface PageGetPageResponse {
    /**
     * 
     * @type {string}
     * @memberof PageGetPageResponse
     */
    'object'?: string;
    /**
     * 
     * @type {string}
     * @memberof PageGetPageResponse
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof PageGetPageResponse
     */
    'created_time'?: string;
    /**
     * 
     * @type {string}
     * @memberof PageGetPageResponse
     */
    'last_edited_time'?: string;
    /**
     * 
     * @type {PageGetPageResponseCreatedBy}
     * @memberof PageGetPageResponse
     */
    'created_by'?: PageGetPageResponseCreatedBy;
    /**
     * 
     * @type {PageGetPageResponseLastEditedBy}
     * @memberof PageGetPageResponse
     */
    'last_edited_by'?: PageGetPageResponseLastEditedBy;
    /**
     * 
     * @type {PageGetPageResponseCover}
     * @memberof PageGetPageResponse
     */
    'cover'?: PageGetPageResponseCover;
    /**
     * 
     * @type {PageGetPageResponseIcon}
     * @memberof PageGetPageResponse
     */
    'icon'?: PageGetPageResponseIcon;
    /**
     * 
     * @type {PageGetPageResponseParent}
     * @memberof PageGetPageResponse
     */
    'parent'?: PageGetPageResponseParent;
    /**
     * 
     * @type {boolean}
     * @memberof PageGetPageResponse
     */
    'archived'?: boolean;
    /**
     * 
     * @type {PageGetPageResponseProperties}
     * @memberof PageGetPageResponse
     */
    'properties'?: PageGetPageResponseProperties;
    /**
     * 
     * @type {string}
     * @memberof PageGetPageResponse
     */
    'url'?: string;
    /**
     * 
     * @type {any}
     * @memberof PageGetPageResponse
     */
    'public_url'?: any;
}

