/*
Notion API

Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PageGetPageResponsePropertiesDescriptionRichTextInner } from './page-get-page-response-properties-description-rich-text-inner';

/**
 * 
 * @export
 * @interface PageGetPageResponsePropertiesDescription
 */
export interface PageGetPageResponsePropertiesDescription {
    /**
     * 
     * @type {string}
     * @memberof PageGetPageResponsePropertiesDescription
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof PageGetPageResponsePropertiesDescription
     */
    'type'?: string;
    /**
     * 
     * @type {Array<PageGetPageResponsePropertiesDescriptionRichTextInner>}
     * @memberof PageGetPageResponsePropertiesDescription
     */
    'rich_text'?: Array<PageGetPageResponsePropertiesDescriptionRichTextInner>;
}

