/*
Notion API

Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * A set of criteria, `direction` and `timestamp` keys, that orders the results. The **only** supported timestamp value is `\"last_edited_time\"`. Supported `direction` values are `\"ascending\"` and `\"descending\"`. If `sort` is not provided, then the most recently edited results are returned first.
 * @export
 * @interface SearchByTitleRequestSort
 */
export interface SearchByTitleRequestSort {
    /**
     * The direction to sort. Possible values include `ascending` and `descending`.
     * @type {string}
     * @memberof SearchByTitleRequestSort
     */
    'direction'?: string;
    /**
     * The name of the timestamp to sort against. Possible values include `last_edited_time`.
     * @type {string}
     * @memberof SearchByTitleRequestSort
     */
    'timestamp'?: string;
}

