/*
Notion API

Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SearchByTitleResponseResultsInner } from './search-by-title-response-results-inner';

/**
 * 
 * @export
 * @interface SearchByTitleResponse
 */
export interface SearchByTitleResponse {
    /**
     * 
     * @type {string}
     * @memberof SearchByTitleResponse
     */
    'object'?: string;
    /**
     * 
     * @type {Array<SearchByTitleResponseResultsInner>}
     * @memberof SearchByTitleResponse
     */
    'results'?: Array<SearchByTitleResponseResultsInner>;
    /**
     * 
     * @type {any}
     * @memberof SearchByTitleResponse
     */
    'next_cursor'?: any;
    /**
     * 
     * @type {boolean}
     * @memberof SearchByTitleResponse
     */
    'has_more'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SearchByTitleResponse
     */
    'type'?: string;
    /**
     * 
     * @type {object}
     * @memberof SearchByTitleResponse
     */
    'page_or_database'?: object;
}

