/*
Notion API

Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SearchByTitleRequestFilter } from './search-by-title-request-filter';
import { SearchByTitleRequestSort } from './search-by-title-request-sort';

/**
 * 
 * @export
 * @interface SearchByTitleRequest
 */
export interface SearchByTitleRequest {
    /**
     * The text that the API compares page and database titles against.
     * @type {string}
     * @memberof SearchByTitleRequest
     */
    'query'?: string;
    /**
     * 
     * @type {SearchByTitleRequestSort}
     * @memberof SearchByTitleRequest
     */
    'sort'?: SearchByTitleRequestSort;
    /**
     * 
     * @type {SearchByTitleRequestFilter}
     * @memberof SearchByTitleRequest
     */
    'filter'?: SearchByTitleRequestFilter;
    /**
     * A `cursor` value returned in a previous response that If supplied, limits the response to results starting after the `cursor`. If not supplied, then the first page of results is returned. Refer to [pagination](https://developers.notion.com/reference/intro#pagination) for more details.
     * @type {string}
     * @memberof SearchByTitleRequest
     */
    'start_cursor'?: string;
    /**
     * The number of items from the full list to include in the response. Maximum: `100`.
     * @type {number}
     * @memberof SearchByTitleRequest
     */
    'page_size'?: number;
}

