/*
Notion API

Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TokenGenerateAccessResponseOwner } from './token-generate-access-response-owner';

/**
 * 
 * @export
 * @interface TokenGenerateAccessResponse
 */
export interface TokenGenerateAccessResponse {
    /**
     * 
     * @type {string}
     * @memberof TokenGenerateAccessResponse
     */
    'access_token'?: string;
    /**
     * 
     * @type {string}
     * @memberof TokenGenerateAccessResponse
     */
    'bot_id'?: string;
    /**
     * 
     * @type {any}
     * @memberof TokenGenerateAccessResponse
     */
    'duplicated_template_id'?: any;
    /**
     * 
     * @type {TokenGenerateAccessResponseOwner}
     * @memberof TokenGenerateAccessResponse
     */
    'owner'?: TokenGenerateAccessResponseOwner;
    /**
     * 
     * @type {string}
     * @memberof TokenGenerateAccessResponse
     */
    'workspace_icon'?: string;
    /**
     * 
     * @type {string}
     * @memberof TokenGenerateAccessResponse
     */
    'workspace_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof TokenGenerateAccessResponse
     */
    'workspace_name'?: string;
}

