/*
Notion API

Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UserGetTokenBotUserResponseBotOwner } from './user-get-token-bot-user-response-bot-owner';

/**
 * 
 * @export
 * @interface UserGetTokenBotUserResponseBot
 */
export interface UserGetTokenBotUserResponseBot {
    /**
     * 
     * @type {UserGetTokenBotUserResponseBotOwner}
     * @memberof UserGetTokenBotUserResponseBot
     */
    'owner'?: UserGetTokenBotUserResponseBotOwner;
}

