/*
Notion API

Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UserGetTokenBotUserResponseBotOwnerUserPerson } from './user-get-token-bot-user-response-bot-owner-user-person';

/**
 * 
 * @export
 * @interface UserGetTokenBotUserResponseBotOwnerUser
 */
export interface UserGetTokenBotUserResponseBotOwnerUser {
    /**
     * 
     * @type {string}
     * @memberof UserGetTokenBotUserResponseBotOwnerUser
     */
    'object'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserGetTokenBotUserResponseBotOwnerUser
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserGetTokenBotUserResponseBotOwnerUser
     */
    'name'?: string;
    /**
     * 
     * @type {any}
     * @memberof UserGetTokenBotUserResponseBotOwnerUser
     */
    'avatar_url'?: any;
    /**
     * 
     * @type {string}
     * @memberof UserGetTokenBotUserResponseBotOwnerUser
     */
    'type'?: string;
    /**
     * 
     * @type {UserGetTokenBotUserResponseBotOwnerUserPerson}
     * @memberof UserGetTokenBotUserResponseBotOwnerUser
     */
    'person'?: UserGetTokenBotUserResponseBotOwnerUserPerson;
}

