/*
Notion API

Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UserGetTokenBotUserResponseBot } from './user-get-token-bot-user-response-bot';

/**
 * 
 * @export
 * @interface UserGetTokenBotUserResponse
 */
export interface UserGetTokenBotUserResponse {
    /**
     * 
     * @type {string}
     * @memberof UserGetTokenBotUserResponse
     */
    'object'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserGetTokenBotUserResponse
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserGetTokenBotUserResponse
     */
    'name'?: string;
    /**
     * 
     * @type {any}
     * @memberof UserGetTokenBotUserResponse
     */
    'avatar_url'?: any;
    /**
     * 
     * @type {string}
     * @memberof UserGetTokenBotUserResponse
     */
    'type'?: string;
    /**
     * 
     * @type {UserGetTokenBotUserResponseBot}
     * @memberof UserGetTokenBotUserResponse
     */
    'bot'?: UserGetTokenBotUserResponseBot;
}

